[project]
name = "ts-pymongo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "pymongo>=4.13.2",
    "python-decouple>=3.8",
]
